name: github-pages-deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to external repo
        uses: peaceiris/actions-gh-pages@v4
        with:
          external_repository: abdulsaheel/vanguards-studio-fe
          publish_dir: ./dist
          publish_branch: gh-pages-2
          personal_token: ${{ secrets.GH_PAGES_DEPLOY_PAT }}
